angular.module('translate').
service('en',[function(){
    this.data = {
        "English": "English",
        "Sinhala": "Sinhala",
        "Tamil":"Tamil",
        "Suniru Lanka":"Suniru Lanka",
        "Many things from a one place":"Many things from a one place",
        "Cakes":"Cakes",
        "Take Aways":"Take Aways",
        "Wedding Halls":"Wedding Halls",
        "About us":"About us",
        "contact us":"contact us",
        "email":"email",
        "Name":"Name",
        "description":"description",
        "aboutUs-msg":"Our goal is to provide our customers the most perfect and quality experince that they would experince in their lives. We know that special events mean a lot to you and we would make it more colorful with our flexible and reliable service",
        "Wedding Halls":"Wedding Halls",
        "Wedding Halls with A/C":"Wedding Halls with A/C",
        "Food Menu":"Food Menu",
        "Wedding Hall":"Wedding Hall",
        "weddingHall-msg":"we arrange it according to your preference just call us",
        "Take Away":"Take Away",
        "Chinese":"Chinese",
        "Indians":"Indians",
        "SriLankan":"SriLankan",
        "BreakFast":"BreakFast",
        "Dinner":"Dinner",
        "Launch":"Launch",
        "Fried Rice":"Fried Rice",
        "French Rice":"French Rice",
        "Rice and Curry":"Rice and Curry",
        "Breads":"Breads",
        "takeAway-msg":"You can order your foods just call us",
        "Wedding Cakes":"Wedding Cakes",
        "Party Cakes":"Party Cakes",
        "Birthday Cakes":"Birthday Cakes",
        "packages":"packages",
        "Wedding Cake":"Wedding Cake",
        "package":"package",
        "Quantity":"Quantity",
        "With Icing":"With Icing",
        "cake-msg":"we ensure that you get the most delciouse cakes...",
        "Call to order":"Call to order",
        "why should you choose Suniru Lanka for your special moments":"Why you should choose Suniru Lanka for your special moments",
        "Reliable service":"Reliable service",
        "Customer Satisfactions":"Customer Satisfactions",
        "Best chefs":"Best chefs",
        "Many choices to pick":"Many choices to pick",
        "Suniru Lanka Wedding Halls":"Suniru Lanka Wedding Halls",
        "The Best wedding and Reception Halls":"The Best wedding and Reception Halls",
        "Delisiouse Foods":"Delisiouse Foods",
        "Pick your choice":"Pick your choice",
        "Customize your menus":"Customize your menus",
        "Choose what your loved ones perfect preference":"Choose what your loved ones perfect preference",
        "What is your taste ?":"What is your taste ?",
        "SriLankan, Indian,Chineese and western menus":"SriLankan, Indian,Chineese and western menus",
        "Submit":"submit"
    };
}]);