angular.module('translate').
service('si',[function(){    
    this.data = {
        "English": "ඉංග්‍රීසි",
        "Sinhala": "සිංහල",
        "Tamil":"දමිළ",
        "Suniru Lanka":"සුනිරු ලංකා",
        "Many things from a one place":"එක් තැනක සිට බොහෝ දේ",
        "Cakes":"කේක්",
        "Take Aways":"රැගෙන යන්න",
        "Wedding Halls":"රැගෙන යන්න",
        "About us":"අපි ගැන",
        "contact us":"අප අමතන්න",
        "email":"විද්‍යුත් තැපෑල",
        "Name":"නම",
        "description":"විස්තර",
        "aboutUs-msg":"අපේ අරමුණ වන්නේ අපගේ ගනුදෙනුකරුවන් ඔවුන්ගේ ජීවිතය තුල නොලද පරිපුර්ණ හා ගුණාත්මක අත්දැකීම් ලබා දීමයි. ඔබගේ විශේෂ සිදුවීම් ඔබට වැදගත් බව අපි දන්නා නිසා අපගේ නම්‍යශීලී හා විශ්වාසවන්ත සේවය මගින් එය තවත් වර්ණවත් කරනු ඇත.",
        "Wedding Halls":"මංගල ශාලා",
        "Wedding Halls with A/C":"වායුසමනය කළ මංගල ශාලා",
        "Food Menu":"ආහාර මෙනුව",
        "Wedding Hall":"මංගල ශාලා",
        "weddingHall-msg":"අප අමතන්න.. ඔබේ කැමැත්ත අනුව අපි එය සංවිධානය කරන්නෙමු",
        "Take Away":"රැගෙන යන්න",
        "Chinese":"චීන",
        "Indians":"ඉන්දියානු",
        "SriLankan":"ශ්‍රී ලාංකික",
        "BreakFast":"උදේ කෑම",
        "Dinner":"රාත්‍රී ආහාරය",
        "Launch":"දිවා ආහාරය",
        "Fried Rice":"ෆ්‍රයිඩ් රයිස්",
        "French Rice":"ප්‍රංශ රයිස්",
        "Rice and Curry":"බත් හා ව්‍යංජන",
        "Breads":"පාන්",
        "takeAway-msg":"ඔබ අප අමතන්න ඔබගේ ආහාර ඇණවුම් කළ හැකිය",
        "Wedding Cakes":"මංගල කේක්",
        "Party Cakes":"උත්සව කේක්",
        "Birthday Cakes":"උපන්දින කේක්",
        "packages":"පැකේජ",
        "Wedding Cake":"මංගල කේක්",
        "package":"පැකේජ",
        "Quantity":"ප්‍රමාණය",
        "With Icing":"අයිසිං සමග",
        "cake-msg":"අපි ඔබට වඩාත් රසවත් කේක් ලබා දීමට සහතික වන්නෙමු...",
        "Call to order":"ඇණවුම් කිරීමට අමතන්න",
	"why should you choose Suniru Lanka for your special moments":"විශේෂ අවස්ථා සදහා සනිරු ලංකා තොර ගන්නේ ඇයි?",
	"Reliable service":"විශ්වාසදායක සේවය",
	"Customer Satisfactions":"පාරිභෝගික තෘප්තිය",
	"Best chefs":"හොඳම සූපවේදීන්",
	"Many choices to pick":"තෝරා ගැනීමට බොහෝ දේ",
	"Suniru Lanka Wedding Halls":"සනිරු ලංකා මංගල ශාලා",
	"The Best wedding and Reception Halls":"හොඳම විවාහ හා උත්සව ශාලා",	
	"Delisiouse Foods":"රසවත් ආහාර",
	"Pick your choice":"ඔබේ තේරීම තෝරා ගන්න",	
	"Customize your menus":"ඔබේ අහර ගොනුව රිසිකරණය කරන්න'",
	"Choose what your loved ones perfect preference":"ඔබේ ආදරය කරන්නාගේ පරිපුර්ණ මනාපය තෝරාගන්න",
	"What is your taste ?":"ඔබගේ රස කුමක්ද ?",
	"SriLankan, Indian,Chineese and western menus":"ශ්‍රී ලංකික, ඉන්දීය, චීන හා බටහිර අහර ගොනු",
    "Submit":"තහවුරු කරන්න"
    };
}]);