angular.module('translate').
service('ta',[function(){
    this.data = {
        "English": "ஆங்கிலம்",
        "Sinhala": "சிங்களம்",
        "Tamil":"தமிழ்",
        "Suniru Lanka":"சுனிரு லங்கா ",
        "Many things from a one place":"ஒரு இடத்தில் இருந்து பல விஷயங்கள்",
        "Cakes":"கேக்குகள்",
        "Take Aways":"கொண்டு செல்ல ",
        "Wedding Halls":"திருமண மண்டபம்",
        "About us":"எங்களை பற்றி",
        "contact us":"எங்களை தொடர்பு கொள்ளவும்",
        "email":"மின்னஞ்சல்",
        "Name":"பெயர்",
        "description":"விளக்கம்",
        "aboutUs-msg":"வாடிக்கையாளர்களுக்கு நேர்த்தியான தரமான சேவையையும் அனுபவங்களையும் வழங்குவதே எங்கள் இலக்கு. எங்கள் நம்பகதரமான சேவைகள் மூலம் உங்கள் வாழ்வின் உன்னதமான தருணங்களை வண்ணமயமாக்குக்கிறோம்.",
        "Wedding Halls":"திருமண மண்டபம்",
        "Wedding Halls with A/C":"குளிரூட்டிகளுடன் கூடிய திருமண மண்டபம் ",
        "Food Menu":"உணவு பட்டியல் ",
        "Wedding Hall":"திருமண மண்டபம்",
        "weddingHall-msg":"உங்கள் விருப்பத்திற்கு ஏற்றவாறு நாங்கள் ஒழுங்கு செய்கின்றோம் ",
        "Take Away":"கொண்டு செல்ல",
        "Chinese":"சீனர்கள் ",
        "Indians":"இந்தியர்கள்",
        "SriLankan":"இலங்கையர் ",
        "BreakFast":"காலை உணவு ",
        "Dinner":"இரவு உணவு ",
        "Launch":"மதிய உணவு ",
        "Fried Rice":"ஃபிரைடு ரைஸ்",
        "French Rice":"பிரஞ்சு ரைஸ்",
        "Rice and Curry":"சோறு  மற்றும் கறி",
        "Breads":"பாண் ",
        "takeAway-msg":"உங்கள் உணவுகளை பெற்றுக்கொள்ள எங்களை அழையுங்கள் ",
        "Wedding Cakes":"திருமண கேக்",
        "Party Cakes":"பார்ட்டி கேக் ",
        "Birthday Cakes":"பிறந்த நாள் கேக் ",
        "packages":"தொகுப்புகள்",
        "Wedding Cake":"திருமண கேக்",
        "package":"தொகுப்புகள்",
        "Quantity":"அளவு",
        "With Icing":"ஐசிங் உடன்",
        "cake-msg":"நீங்கள் மிக சுவையான கேக்குகளை பெற்று கொள்வீர்கள் என  நாங்கள் உறுதி செய்கின்றோம் ",
        "Call to order":"ஓர்டர்களுக்கு அழையுங்கள் ",
		"why should you choose Suniru Lanka for your special moments":" நீங்கள் சுனிரு லங்காவை விஷேட நிகழ்வுகளுக்கு தெரிவு செய்வதன் காரணம் என்ன ",
       "Reliable service":"நம்பகமான சேவைகள்",
       "Customer Satisfactions":"வாடிக்கையாளர் திருப்தி",
       "Best chefs":"சிறந்த சமையல்காரர்",
       "Many choices to pick":"பல தேர்வுகளுக்கு",
	   "Suniru Lanka Wedding Halls":"சுனிர் லங்கா திருமண மண்டபம்",
	   "The Best wedding and Reception Halls":"சிறந்த திருமண மற்றும் வரவேற்பறை",
       "Delisiouse Foods":"சுவையான உணவுகள்",
       "Pick your choice":"உங்கள் விருப்பத்தைத் தேர்ந்தெடுங்கள்",
        "Customize your menus":"உங்கள் பட்டியலை  தனிப்பயனாக்கவும்",
        "Choose what your loved ones perfect preference":"உங்கள் அன்புக்குரியவர்களின் சரியான விருப்பம் என்ன என்பதை தேர்வு செய்யவும்",
       "What is your taste ?":"உங்கள் சுவை என்ன?",
       "SriLankan, Indian,Chineese and western menus":"இலங்கைய , இந்திய, சீன மற்றும் மேற்கத்தைய உணவு பட்டியல் ",
       "Submit":"சமர்ப்பி"
    };
}]);